### ISSUE TITLE
TODO for Scratch Blocks

### ISSUE THREAD

**Issue by JoshuaLowe1002** [AllAboutCode/EduBlocks#70]
- [x] Add custom PXT fields
- [x] Sort out block alignment
- [x] Design updated navbar with a setting cog for options that are not "core" to using EduBlocks 
- [x] Finish sorting fields out
- [x] Fix the variable category
- [x] Release BETA
